// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct TicTacToeSailsClientProgram;
impl sails_rs::client::Program for TicTacToeSailsClientProgram {}
pub trait TicTacToeSailsClient {
    type Env: sails_rs::client::GearEnv;
    fn game(&self) -> sails_rs::client::Service<game::GameImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> TicTacToeSailsClient
    for sails_rs::client::Actor<TicTacToeSailsClientProgram, E>
{
    type Env = E;
    fn game(&self) -> sails_rs::client::Service<game::GameImpl, Self::Env> {
        self.service(stringify!(Game))
    }
}
pub trait TicTacToeSailsClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<TicTacToeSailsClientProgram, io::Create, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> TicTacToeSailsClientCtors
    for sails_rs::client::Deployment<TicTacToeSailsClientProgram, E>
{
    type Env = E;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<TicTacToeSailsClientProgram, io::Create, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create () -> ());
}

pub mod game {
    use super::*;
    pub trait Game {
        type Env: sails_rs::client::GearEnv;
        fn cancel_lobby(
            &mut self,
            lobby_id: u64,
        ) -> sails_rs::client::PendingCall<io::CancelLobby, Self::Env>;
        fn commit_move(
            &mut self,
            match_id: u64,
            round: u8,
            input: CommitInput,
        ) -> sails_rs::client::PendingCall<io::CommitMove, Self::Env>;
        fn create_lobby(&mut self) -> sails_rs::client::PendingCall<io::CreateLobby, Self::Env>;
        fn forfeit_match(
            &mut self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::ForfeitMatch, Self::Env>;
        fn join_lobby(
            &mut self,
            lobby_id: u64,
        ) -> sails_rs::client::PendingCall<io::JoinLobby, Self::Env>;
        fn reveal_move(
            &mut self,
            match_id: u64,
            round: u8,
            input: RevealInput,
        ) -> sails_rs::client::PendingCall<io::RevealMove, Self::Env>;
        fn settle_round(
            &mut self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::SettleRound, Self::Env>;
        fn active_match(
            &self,
            player: ActorId,
        ) -> sails_rs::client::PendingCall<io::ActiveMatch, Self::Env>;
        fn leaderboard(
            &self,
            limit: u16,
        ) -> sails_rs::client::PendingCall<io::Leaderboard, Self::Env>;
        fn match_by_id(
            &self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::MatchById, Self::Env>;
        fn open_lobbies(&self) -> sails_rs::client::PendingCall<io::OpenLobbies, Self::Env>;
        fn player_stats(
            &self,
            player: ActorId,
        ) -> sails_rs::client::PendingCall<io::PlayerStats, Self::Env>;
        fn version(&self) -> sails_rs::client::PendingCall<io::Version, Self::Env>;
    }
    pub struct GameImpl;
    impl<E: sails_rs::client::GearEnv> Game for sails_rs::client::Service<GameImpl, E> {
        type Env = E;
        fn cancel_lobby(
            &mut self,
            lobby_id: u64,
        ) -> sails_rs::client::PendingCall<io::CancelLobby, Self::Env> {
            self.pending_call((lobby_id,))
        }
        fn commit_move(
            &mut self,
            match_id: u64,
            round: u8,
            input: CommitInput,
        ) -> sails_rs::client::PendingCall<io::CommitMove, Self::Env> {
            self.pending_call((match_id, round, input))
        }
        fn create_lobby(&mut self) -> sails_rs::client::PendingCall<io::CreateLobby, Self::Env> {
            self.pending_call(())
        }
        fn forfeit_match(
            &mut self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::ForfeitMatch, Self::Env> {
            self.pending_call((match_id,))
        }
        fn join_lobby(
            &mut self,
            lobby_id: u64,
        ) -> sails_rs::client::PendingCall<io::JoinLobby, Self::Env> {
            self.pending_call((lobby_id,))
        }
        fn reveal_move(
            &mut self,
            match_id: u64,
            round: u8,
            input: RevealInput,
        ) -> sails_rs::client::PendingCall<io::RevealMove, Self::Env> {
            self.pending_call((match_id, round, input))
        }
        fn settle_round(
            &mut self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::SettleRound, Self::Env> {
            self.pending_call((match_id,))
        }
        fn active_match(
            &self,
            player: ActorId,
        ) -> sails_rs::client::PendingCall<io::ActiveMatch, Self::Env> {
            self.pending_call((player,))
        }
        fn leaderboard(
            &self,
            limit: u16,
        ) -> sails_rs::client::PendingCall<io::Leaderboard, Self::Env> {
            self.pending_call((limit,))
        }
        fn match_by_id(
            &self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::MatchById, Self::Env> {
            self.pending_call((match_id,))
        }
        fn open_lobbies(&self) -> sails_rs::client::PendingCall<io::OpenLobbies, Self::Env> {
            self.pending_call(())
        }
        fn player_stats(
            &self,
            player: ActorId,
        ) -> sails_rs::client::PendingCall<io::PlayerStats, Self::Env> {
            self.pending_call((player,))
        }
        fn version(&self) -> sails_rs::client::PendingCall<io::Version, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(CancelLobby (lobby_id: u64) -> Result<(), super::GameError>);
        sails_rs::io_struct_impl!(CommitMove (match_id: u64, round: u8, input: super::CommitInput) -> Result<super::MatchView, super::GameError>);
        sails_rs::io_struct_impl!(CreateLobby () -> Result<super::Lobby, super::GameError>);
        sails_rs::io_struct_impl!(ForfeitMatch (match_id: u64) -> Result<super::MatchView, super::GameError>);
        sails_rs::io_struct_impl!(JoinLobby (lobby_id: u64) -> Result<super::MatchView, super::GameError>);
        sails_rs::io_struct_impl!(RevealMove (match_id: u64, round: u8, input: super::RevealInput) -> Result<super::MatchView, super::GameError>);
        sails_rs::io_struct_impl!(SettleRound (match_id: u64) -> Result<super::MatchView, super::GameError>);
        sails_rs::io_struct_impl!(ActiveMatch (player: ActorId) -> Option<super::MatchView>);
        sails_rs::io_struct_impl!(Leaderboard (limit: u16) -> Vec<super::LeaderboardEntry>);
        sails_rs::io_struct_impl!(MatchById (match_id: u64) -> Result<super::MatchView, super::GameError>);
        sails_rs::io_struct_impl!(OpenLobbies () -> Vec<super::Lobby>);
        sails_rs::io_struct_impl!(PlayerStats (player: ActorId) -> super::PlayerStats);
        sails_rs::io_struct_impl!(Version () -> u32);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum GameEvents {
            LobbyCreated {
                lobby_id: u64,
                host: ActorId,
            },
            LobbyJoined {
                lobby_id: u64,
                match_id: u64,
                host: ActorId,
                guest: ActorId,
            },
            LobbyCancelled {
                lobby_id: u64,
                host: ActorId,
            },
            MoveCommitted {
                match_id: u64,
                round: u8,
                player: ActorId,
            },
            MoveRevealed {
                match_id: u64,
                round: u8,
                player: ActorId,
            },
            RoundSettled {
                match_id: u64,
                round: u8,
                board: [Mark; 9],
                outcome: Option<MatchOutcome>,
            },
            MatchFinished {
                match_id: u64,
                outcome: MatchOutcome,
            },
            LeaderboardUpdated {
                player: ActorId,
                stats: PlayerStats,
            },
        }
        impl sails_rs::client::Event for GameEvents {
            const EVENT_NAMES: &'static [Route] = &[
                "LobbyCreated",
                "LobbyJoined",
                "LobbyCancelled",
                "MoveCommitted",
                "MoveRevealed",
                "RoundSettled",
                "MatchFinished",
                "LeaderboardUpdated",
            ];
        }
        impl sails_rs::client::ServiceWithEvents for GameImpl {
            type Event = GameEvents;
        }
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum GameError {
    AlreadyInActiveMatch,
    AlreadyHostingLobby,
    LobbyNotFound,
    CannotJoinOwnLobby,
    MatchNotFound,
    NotMatchParticipant,
    InvalidRound,
    RoundAlreadySettled,
    CommitmentAlreadySubmitted,
    RevealAlreadySubmitted,
    CommitmentMissing,
    RevealMissing,
    InvalidRevealHash,
    MatchAlreadyFinished,
    CellOutOfBounds,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct CommitInput {
    pub hash: [u8; 32],
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct MatchView {
    pub id: u64,
    pub host: ActorId,
    pub guest: ActorId,
    pub board: [Mark; 9],
    pub lifecycle: MatchLifecycle,
    pub next_round: u8,
    pub round: RoundView,
    pub outcome: Option<MatchOutcome>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum Mark {
    Empty,
    X,
    O,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum MatchLifecycle {
    Active,
    Finished,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct RoundView {
    pub round: u8,
    pub host_committed: bool,
    pub guest_committed: bool,
    pub host_revealed: bool,
    pub guest_revealed: bool,
    pub settled: bool,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct MatchOutcome {
    pub result: MatchResultKind,
    pub reason: MatchEndReason,
    pub winner: Option<ActorId>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum MatchResultKind {
    HostWon,
    GuestWon,
    Draw,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum MatchEndReason {
    LineCompleted,
    BoardFull,
    SimultaneousWin,
    InvalidCell,
    Forfeit,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Lobby {
    pub id: u64,
    pub host: ActorId,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct RevealInput {
    pub cell: u8,
    pub salt: [u8; 32],
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct LeaderboardEntry {
    pub player: ActorId,
    pub stats: PlayerStats,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct PlayerStats {
    pub matches_played: u32,
    pub wins: u32,
    pub losses: u32,
    pub draws: u32,
}
