// THIS FILE IS AUTO-GENERATED by scripts/scaffold-client.ts
// Regenerate: cd frontend && npx tsx ../scripts/scaffold-client.ts
// Source IDL: src/assets/tic_tac_toe_sails_client.idl
// Custom helpers should go in a separate file (e.g., sails-helpers.ts)

import type { GearApi } from "@gear-js/api";
import idlRaw from "@/assets/tic_tac_toe_sails_client.idl?raw";

let cachedSails: Promise<unknown> | null = null;
let cachedApi: GearApi | null = null;

export async function initSails(api: GearApi) {
  // Invalidate cache if api instance changed (fixes stale connection after reconnect)
  if (cachedSails && cachedApi !== api) {
    cachedSails = null;
  }
  if (!cachedSails) {
    cachedApi = api;
    cachedSails = (async () => {
      const [{ Sails }, { SailsIdlParser }] = await Promise.all([
        import("sails-js"),
        import("sails-js-parser"),
      ]);
      const parser = await SailsIdlParser.new();
      const sails = new Sails(parser);
      sails.setApi(api);
      sails.parseIdl(idlRaw);

      const programId = import.meta.env.VITE_PROGRAM_ID;
      if (programId) {
        sails.setProgramId(programId as `0x${string}`);
      }

      return sails;
    })().catch((err) => {
      cachedSails = null;
      cachedApi = null;
      throw err;
    });
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return cachedSails as Promise<any>;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function getService(sails: any): any {
  return sails?.services?.Game ?? sails?.services?.game;
}

// -- Queries --

export async function queryActiveMatch(api: GearApi, player: string): Promise<unknown | null> {
  const sails = await initSails(api);
  const service = getService(sails);
  return service.queries.ActiveMatch(player).call();
}

export async function queryLeaderboard(api: GearApi, limit: number): Promise<unknown[]> {
  const sails = await initSails(api);
  const service = getService(sails);
  return service.queries.Leaderboard(limit).call();
}

export async function queryMatchById(api: GearApi, match_id: string): Promise<unknown> {
  const sails = await initSails(api);
  const service = getService(sails);
  return service.queries.MatchById(match_id).call();
}

export async function queryOpenLobbies(api: GearApi): Promise<unknown[]> {
  const sails = await initSails(api);
  const service = getService(sails);
  return service.queries.OpenLobbies().call();
}

export async function queryPlayerStats(api: GearApi, player: string): Promise<unknown> {
  const sails = await initSails(api);
  const service = getService(sails);
  return service.queries.PlayerStats(player).call();
}

export async function queryVersion(api: GearApi): Promise<number> {
  const sails = await initSails(api);
  const service = getService(sails);
  return service.queries.Version().call();
}

// -- Transactions --

export async function txCancelLobby(
  api: GearApi,
  account: string,
  lobby_id: string,
  signer?: unknown
): Promise<unknown> {
  const sails = await initSails(api);
  const service = getService(sails);
  const tx = service.functions.CancelLobby(lobby_id);
  const result = await tx
    .withAccount(account, signer ? { signer } : undefined)
    .calculateGas()
    .then(() => tx.signAndSend());
  return result.response();
}

export async function txCommitMove(
  api: GearApi,
  account: string,
  match_id: string,
  round: number,
  input: unknown,
  signer?: unknown
): Promise<unknown> {
  const sails = await initSails(api);
  const service = getService(sails);
  const tx = service.functions.CommitMove(match_id, round, input);
  const result = await tx
    .withAccount(account, signer ? { signer } : undefined)
    .calculateGas()
    .then(() => tx.signAndSend());
  return result.response();
}

export async function txCreateLobby(
  api: GearApi,
  account: string,
  signer?: unknown
): Promise<unknown> {
  const sails = await initSails(api);
  const service = getService(sails);
  const tx = service.functions.CreateLobby();
  const result = await tx
    .withAccount(account, signer ? { signer } : undefined)
    .calculateGas()
    .then(() => tx.signAndSend());
  return result.response();
}

export async function txForfeitMatch(
  api: GearApi,
  account: string,
  match_id: string,
  signer?: unknown
): Promise<unknown> {
  const sails = await initSails(api);
  const service = getService(sails);
  const tx = service.functions.ForfeitMatch(match_id);
  const result = await tx
    .withAccount(account, signer ? { signer } : undefined)
    .calculateGas()
    .then(() => tx.signAndSend());
  return result.response();
}

export async function txJoinLobby(
  api: GearApi,
  account: string,
  lobby_id: string,
  signer?: unknown
): Promise<unknown> {
  const sails = await initSails(api);
  const service = getService(sails);
  const tx = service.functions.JoinLobby(lobby_id);
  const result = await tx
    .withAccount(account, signer ? { signer } : undefined)
    .calculateGas()
    .then(() => tx.signAndSend());
  return result.response();
}

export async function txRevealMove(
  api: GearApi,
  account: string,
  match_id: string,
  round: number,
  input: unknown,
  signer?: unknown
): Promise<unknown> {
  const sails = await initSails(api);
  const service = getService(sails);
  const tx = service.functions.RevealMove(match_id, round, input);
  const result = await tx
    .withAccount(account, signer ? { signer } : undefined)
    .calculateGas()
    .then(() => tx.signAndSend());
  return result.response();
}

export async function txSettleRound(
  api: GearApi,
  account: string,
  match_id: string,
  signer?: unknown
): Promise<unknown> {
  const sails = await initSails(api);
  const service = getService(sails);
  const tx = service.functions.SettleRound(match_id);
  const result = await tx
    .withAccount(account, signer ? { signer } : undefined)
    .calculateGas()
    .then(() => tx.signAndSend());
  return result.response();
}

/** Get the raw IDL text for the debug panel. */
export function getIdlText(): string {
  return idlRaw;
}
